import React from "react";
import { PilotsList } from "./PilotsList";

export default {
  title: "Components/PilotsList",
  component: PilotsList,
};

const Template = (args) => <PilotsList {...args} />;
export const Default = Template.bind({});

Default.args = {
  pilots: [
    {
      id: "1",
      airline: "Rivera State 32/106",
      fleet: "737",
      seat: "CPT",
      domicile: "GEG",
      firstName: "John",
      lastName: "Smith",
      email: "goseahawks@outlook.com",
      areacode: "123",
      prefix: "456",
      suffix: "7890",
      address1: "795 Folsom Ave",
      address2: "Suite 600",
      city: "San Francisco",
      state: "CA",
      postalCode: "94107",
      photo: "john-smith.jpeg",
      socials: "Twitter, Inc.",
    },
    {
      id: "2",
      airline: "Rivera State 32/106",
      fleet: "737",
      seat: "CPT",
      domicile: "GEG",
      firstName: "Alex",
      lastName: "Johnatan",
      email: "goseahawks@outlook.com",
      areacode: "123",
      prefix: "456",
      suffix: "7890",
      address1: "795 Folsom Ave",
      address2: "Suite 600",
      city: "San Francisco",
      state: "CA",
      postalCode: "94107",
      photo: "alex-johnathan.jpeg",
      socials: "Twitter, Inc.",
    },
    {
      id: "3",
      airline: "Rivera State 32/106",
      fleet: "737",
      seat: "CPT",
      domicile: "GEG",
      firstName: "Monica",
      lastName: "Smith",
      email: "goseahawks@outlook.com",
      areacode: "123",
      prefix: "456",
      suffix: "7890",
      address1: "795 Folsom Ave",
      address2: "Suite 600",
      city: "San Francisco",
      state: "CA",
      postalCode: "94107",
      photo: "monica-smith.jpeg",
      socials: "Twitter, Inc.",
    },
    {
      id: "4",
      airline: "Rivera State 32/106",
      fleet: "737",
      seat: "CPT",
      domicile: "GEG",
      firstName: "Michael",
      lastName: "Zimber",
      email: "goseahawks@outlook.com",
      areacode: "123",
      prefix: "456",
      suffix: "7890",
      address1: "795 Folsom Ave",
      address2: "Suite 600",
      city: "San Francisco",
      state: "CA",
      postalCode: "94107",
      photo: "michael-zimber.jpeg",
      socials: "Twitter, Inc.",
    },
    {
      id: "5",
      airline: "Rivera State 32/106",
      fleet: "737",
      seat: "CPT",
      domicile: "GEG",
      firstName: "Sandra",
      lastName: "Smith",
      email: "goseahawks@outlook.com",
      areacode: "123",
      prefix: "456",
      suffix: "7890",
      address1: "795 Folsom Ave",
      address2: "Suite 600",
      city: "San Francisco",
      state: "CA",
      postalCode: "94107",
      photo: "sandra-smith.jpeg",
      socials: "Twitter, Inc.",
    },
    {
      id: "6",
      airline: "Rivera State 32/106",
      fleet: "737",
      seat: "CPT",
      domicile: "GEG",
      firstName: "Janet",
      lastName: "Carton",
      email: "goseahawks@outlook.com",
      areacode: "123",
      prefix: "456",
      suffix: "7890",
      address1: "795 Folsom Ave",
      address2: "Suite 600",
      city: "San Francisco",
      state: "CA",
      postalCode: "94107",
      photo: "janet-carton.jpeg",
      socials: "Twitter, Inc.",
    },
  ],
};
